<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Activity, ArrowRight, CheckCircle2, CircleGauge, Cpu, ListTree } from '@lucide/vue'
import { api, type ApplicationSettings, type DashboardData, type Device, type EngineState } from '../api'
import AppShell from '../components/AppShell.vue'

defineProps<{ theme: 'light' | 'dark' }>(); const emit = defineEmits<{ toggleTheme: [] }>()
const engine = ref<EngineState | null>(null); const devices = ref<Device[]>([]); const dashboard = ref<DashboardData | null>(null); const settings = ref<ApplicationSettings | null>(null); const changing = ref(false)
const healthyDevices = computed(() => dashboard.value?.healthy_devices ?? devices.value.filter(item => item.health_status === 'healthy').length)
const maxBucket = computed(() => Math.max(1, ...(dashboard.value?.series.map(item => item.total) ?? [1])))
async function load() { try { [engine.value, devices.value, dashboard.value, settings.value] = await Promise.all([api.engine(), api.devices(), api.dashboard(), api.settings()]) } catch { /* shell reports API availability */ } }
async function transition() { if (!engine.value) return; changing.value = true; try { engine.value = engine.value.desired_state === 'active' ? await api.pauseEngine() : await api.resumeEngine(); dashboard.value = await api.dashboard() } finally { changing.value = false } }
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
onMounted(load)
</script>

<template><AppShell :theme="theme" @toggle-theme="emit('toggleTheme')">
  <section class="page-heading"><div><p class="eyebrow">OPERATIONS / OVERVIEW</p><h1>Wake orchestration</h1><p>Control and observe wake requests across segmented networks.</p></div><div class="heading-actions"><RouterLink class="secondary-button button-link" to="/listeners">Configure listeners</RouterLink><button class="primary-button button-link" :disabled="!engine || changing" @click="transition">{{ engine?.desired_state === 'active' ? 'Pause engine' : 'Resume engine' }}</button></div></section>
  <section class="metric-grid" aria-label="Platform metrics">
    <article class="metric-card"><div class="metric-title"><span class="metric-glyph"><CircleGauge :size="14" /></span><span>Engine</span><span class="tag paused">{{ engine?.observed_state ?? 'LOADING' }}</span></div><strong>{{ engine?.desired_state ?? 'Checking' }}</strong><p>Runtime control plane state</p></article>
    <article class="metric-card"><div class="metric-title"><span class="metric-glyph"><ListTree :size="14" /></span><span>Active listeners</span></div><strong>{{ engine?.active_listeners ?? 0 }} <small>/ {{ engine?.enabled_listeners ?? 0 }}</small></strong><p>UDP range <code>{{ settings?.udp_port_start ?? '—' }}–{{ settings?.udp_port_end ?? '—' }}</code></p></article>
    <article class="metric-card"><div class="metric-title"><span class="metric-glyph"><CheckCircle2 :size="14" /></span><span>Wake success</span></div><strong>{{ dashboard?.success_rate == null ? '—' : `${dashboard.success_rate}%` }}</strong><p>{{ dashboard?.total_requests ?? 0 }} requests in the last 24 hours</p></article>
    <article class="metric-card"><div class="metric-title"><span class="metric-glyph"><Cpu :size="14" /></span><span>Device health</span></div><strong>{{ healthyDevices }} <small>/ {{ dashboard?.total_devices ?? devices.length }}</small></strong><p>Healthy connection tests</p></article>
  </section>
  <section class="dashboard-grid"><article class="panel chart-panel"><div class="panel-heading"><div><h2>Requests over time</h2><p>Wake outcomes for the last 24 hours</p></div><span class="live-chip">{{ dashboard?.total_requests ?? 0 }} TOTAL</span></div><div class="event-chart"><div v-for="bucket in dashboard?.series ?? []" :key="bucket.start" class="chart-bucket" :title="`${formatDate(bucket.start)} — ${bucket.total} requests`"><i class="chart-failed" :style="{ height: `${(bucket.failed / maxBucket) * 100}%` }"></i><i class="chart-limited" :style="{ height: `${(bucket.rate_limited / maxBucket) * 100}%` }"></i><i class="chart-success" :style="{ height: `${(bucket.success / maxBucket) * 100}%` }"></i></div><div v-if="!dashboard?.total_requests" class="chart-empty-copy"><Activity :size="20" /><strong>No wake activity in this period</strong><span>Validated requests will appear here automatically.</span></div></div><div class="chart-legend"><span><i class="success"></i>Success {{ dashboard?.success ?? 0 }}</span><span><i class="failed"></i>Failed {{ dashboard?.failed ?? 0 }}</span><span><i class="limited"></i>Rate limited {{ dashboard?.rate_limited ?? 0 }}</span></div></article><article class="panel flow-panel"><div class="panel-heading"><div><h2>Live architecture</h2><p>Current request path</p></div><span class="live-chip">{{ engine?.observed_state ?? 'IDLE' }}</span></div><div class="flow"><div class="flow-node"><span>01</span><div><strong>Guacamole / PAM</strong><small>UDP magic packet</small></div></div><i></i><div class="flow-node"><span>02</span><div><strong>WOLT listener</strong><small>Source + packet validation</small></div></div><i></i><div class="flow-node"><span>03</span><div><strong>Edge device</strong><small>Native wake command</small></div></div></div><RouterLink class="text-button" to="/architecture">Explore architecture <ArrowRight :size="13" /></RouterLink></article></section>
  <section class="panel events-panel"><div class="panel-heading"><div><h2>Recent wake events</h2><p>Latest translated requests and outcomes</p></div><RouterLink class="text-button" to="/events">View all events <ArrowRight :size="13" /></RouterLink></div><div class="table-wrap"><table><thead><tr><th>Outcome</th><th>MAC address</th><th>Mapping</th><th>Edge device</th><th>Latency</th><th>Occurred</th></tr></thead><tbody><tr v-for="item in dashboard?.recent_events ?? []" :key="item.id"><td><span class="status-pill" :data-state="item.result_code">{{ item.result_code.replace('_', ' ') }}</span></td><td><code>{{ item.mac_address }}</code></td><td>{{ item.mapping_name }}</td><td>{{ item.device_name }}</td><td>{{ item.duration_ms === null ? '—' : `${item.duration_ms} ms` }}</td><td>{{ formatDate(item.occurred_at) }}</td></tr><tr v-if="!dashboard?.recent_events.length"><td colspan="6"><div class="empty-table"><Activity :size="20" /><strong>No wake events yet</strong><small>Events are persisted after the engine receives a validated request.</small></div></td></tr></tbody></table></div></section>
</AppShell></template>
