<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { CircleGauge, LoaderCircle, Pause, Play, RefreshCw, RadioTower } from '@lucide/vue'
import { api, readableError, type EngineState, type Listener } from '../api'
import AppShell from '../components/AppShell.vue'
defineProps<{ theme: 'light' | 'dark' }>(); const emit = defineEmits<{ toggleTheme: [] }>()
const engine = ref<EngineState | null>(null); const listeners = ref<Listener[]>([]); const loading = ref(true); const changing = ref(false); const error = ref('')
const isActive = computed(() => engine.value?.desired_state === 'active')
async function load() { loading.value = true; try { [engine.value, listeners.value] = await Promise.all([api.engine(), api.listeners()]); error.value = '' } catch (reason) { error.value = readableError(reason) } finally { loading.value = false } }
async function transition() { changing.value = true; try { engine.value = isActive.value ? await api.pauseEngine() : await api.resumeEngine(); listeners.value = await api.listeners(); error.value = '' } catch (reason) { error.value = readableError(reason) } finally { changing.value = false } }
onMounted(load)
</script>
<template><AppShell :theme="theme" @toggle-theme="emit('toggleTheme')"><section class="page-heading"><div><p class="eyebrow">WAKE ENGINE / CONTROL</p><h1>Engine control</h1><p>Pause or reconcile UDP listeners without stopping the management container.</p></div><div class="heading-actions"><button class="secondary-button button-link" @click="load"><RefreshCw :size="15" /> Refresh</button><button class="primary-button button-link" :disabled="changing || loading" @click="transition"><LoaderCircle v-if="changing" class="spin" :size="15" /><Pause v-else-if="isActive" :size="15" /><Play v-else :size="15" />{{ isActive ? 'Pause engine' : 'Resume engine' }}</button></div></section><p v-if="error" class="form-error page-error">{{ error }}</p><section v-if="loading" class="panel loading-panel"><LoaderCircle class="spin" /> Loading engine state…</section><template v-else-if="engine"><section class="engine-hero panel"><div class="engine-orb" :data-state="engine.observed_state"><CircleGauge :size="34" /></div><div><span class="status-pill" :data-state="engine.observed_state">{{ engine.observed_state }}</span><h2>Desired state: {{ engine.desired_state }}</h2><p>{{ engine.active_listeners }} active of {{ engine.enabled_listeners }} enabled listeners</p><small v-if="engine.last_transition_at">Last transition {{ new Date(engine.last_transition_at).toLocaleString() }}</small><small v-if="engine.last_error" class="danger-text">{{ engine.last_error }}</small></div></section><section class="panel operations-table"><header><span>Runtime listeners</span><strong>{{ listeners.length }} configured</strong></header><div class="engine-list"><article v-for="item in listeners" :key="item.id"><RadioTower :size="17" /><div><strong>{{ item.name }}</strong><small>UDP {{ item.udp_port }} · {{ item.device_name }}</small></div><span class="status-pill" :data-state="item.status">{{ item.status }}</span><code v-if="item.last_error">{{ item.last_error }}</code></article><p v-if="!listeners.length">No mappings have been configured.</p></div></section></template></AppShell></template>
