<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ChevronDown, ChevronLeft, ChevronRight, Download, LoaderCircle, RefreshCw, Search } from '@lucide/vue'
import { api, downloadEventsCsv, readableError, type Page, type WakeEvent } from '../api'
import AppShell from '../components/AppShell.vue'

defineProps<{ theme: 'light' | 'dark' }>(); const emit = defineEmits<{ toggleTheme: [] }>()
const data = ref<Page<WakeEvent>>({ items: [], page: 1, page_size: 25, total: 0, pages: 1 })
const loading = ref(true); const exporting = ref(false); const error = ref(''); const expanded = ref<string | null>(null)
const filters = reactive({ query: '', result_code: '', occurred_after: '', occurred_before: '' })
function params(page = data.value.page) { return { page, page_size: data.value.page_size, query: filters.query, result_code: filters.result_code, occurred_after: filters.occurred_after ? new Date(filters.occurred_after).toISOString() : '', occurred_before: filters.occurred_before ? new Date(filters.occurred_before).toISOString() : '' } }
async function load(page = 1) { loading.value = true; error.value = ''; try { data.value = await api.events(params(page)) } catch (reason) { error.value = readableError(reason) } finally { loading.value = false } }
async function exportCsv() { exporting.value = true; error.value = ''; try { await downloadEventsCsv(params(1)) } catch (reason) { error.value = readableError(reason) } finally { exporting.value = false } }
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'medium' }).format(new Date(value)) }
onMounted(() => load())
</script>

<template><AppShell :theme="theme" @toggle-theme="emit('toggleTheme')">
  <section class="page-heading"><div><p class="eyebrow">OBSERVE / EVENTS</p><h1>Wake event explorer</h1><p>Search translated wake requests, outcomes, sources, and end-to-end latency.</p></div><button class="secondary-button button-link" :disabled="exporting" @click="exportCsv"><LoaderCircle v-if="exporting" class="spin" :size="15" /><Download v-else :size="15" /> Export CSV</button></section>
  <form class="panel filter-toolbar" @submit.prevent="load(1)"><label class="filter-search"><Search :size="15" /><input v-model.trim="filters.query" placeholder="MAC, source IP, or correlation ID" /></label><select v-model="filters.result_code" aria-label="Outcome"><option value="">All outcomes</option><option value="success">Success</option><option value="failed">Any failure</option><option value="rate_limited">Rate limited</option><option value="ssh_connection_failed">SSH connection failed</option><option value="ssh_timeout">SSH timeout</option><option value="ssh_authentication_failed">SSH authentication failed</option><option value="host_key_verification_failed">Host key failed</option><option value="command_failed">Command failed</option></select><label>From<input v-model="filters.occurred_after" type="datetime-local" /></label><label>To<input v-model="filters.occurred_before" type="datetime-local" /></label><button class="primary-button" type="submit"><RefreshCw :size="14" /> Apply</button></form>
  <p v-if="error" class="form-error page-error">{{ error }}</p>
  <section class="panel operations-table observation-table"><header><span>{{ data.total }} persisted events</span><strong>Newest first</strong></header><div class="table-wrap"><table><thead><tr><th>Outcome</th><th>MAC address</th><th>Mapping</th><th>Edge device</th><th>Source</th><th>Latency</th><th>Occurred</th><th></th></tr></thead><tbody><template v-for="item in data.items" :key="item.id"><tr><td><span class="status-pill" :data-state="item.result_code">{{ item.result_code.replace('_', ' ') }}</span></td><td><code>{{ item.mac_address }}</code></td><td>{{ item.mapping_name }}</td><td>{{ item.device_name }}</td><td><code>{{ item.source_ip }}:{{ item.source_port }}</code></td><td>{{ item.duration_ms === null ? '—' : `${item.duration_ms} ms` }}</td><td>{{ formatDate(item.occurred_at) }}</td><td><button class="row-detail-button" :aria-expanded="expanded === item.id" @click="expanded = expanded === item.id ? null : item.id"><ChevronDown :size="14" /></button></td></tr><tr v-if="expanded === item.id" class="detail-row"><td colspan="8"><div><span>Correlation ID <code>{{ item.correlation_id }}</code></span><span>Event type <code>{{ item.event_type }}</code></span><span>Mapping ID <code>{{ item.mapping_id }}</code></span><span>Device ID <code>{{ item.device_id }}</code></span></div></td></tr></template><tr v-if="!loading && !data.items.length"><td colspan="8"><div class="empty-table"><Search :size="20" /><strong>No matching wake events</strong><small>Adjust the filters or send a wake request.</small></div></td></tr><tr v-if="loading"><td colspan="8"><div class="empty-table"><LoaderCircle class="spin" :size="20" /><strong>Loading events…</strong></div></td></tr></tbody></table></div><footer class="pagination"><span>Page {{ data.page }} of {{ data.pages }}</span><div><button :disabled="loading || data.page <= 1" @click="load(data.page - 1)"><ChevronLeft :size="15" /> Previous</button><button :disabled="loading || data.page >= data.pages" @click="load(data.page + 1)">Next <ChevronRight :size="15" /></button></div></footer></section>
</AppShell></template>
