<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { CheckCircle2, Copy, LoaderCircle, Pencil, Plus, RadioTower, Trash2, X } from '@lucide/vue'
import { api, readableError, type Device, type Listener } from '../api'
import AppShell from '../components/AppShell.vue'

defineProps<{ theme: 'light' | 'dark' }>(); const emit = defineEmits<{ toggleTheme: [] }>()
const listeners = ref<Listener[]>([]); const devices = ref<Device[]>([]); const loading = ref(true); const error = ref(''); const panelOpen = ref(false); const editingId = ref<string | null>(null); const saving = ref(false)
const form = reactive({ version: 1, deviceId: '', name: '', description: '', autoPort: true, udpPort: 40000, sourceIp: '', interfaceName: '', gatewayIp: '', enabled: false })
const isEditing = computed(() => editingId.value !== null); const enabledDevices = computed(() => devices.value.filter(item => item.enabled))
async function load() { loading.value = true; error.value = ''; try { [listeners.value, devices.value] = await Promise.all([api.listeners(), api.devices()]) } catch (reason) { error.value = readableError(reason) } finally { loading.value = false } }
function openCreate() { editingId.value = null; Object.assign(form, { version: 1, deviceId: enabledDevices.value[0]?.id ?? '', name: '', description: '', autoPort: true, udpPort: 40000, sourceIp: '', interfaceName: '', gatewayIp: '', enabled: false }); panelOpen.value = true }
function openEdit(item: Listener) { editingId.value = item.id; Object.assign(form, { version: item.version, deviceId: item.device_id, name: item.name, description: item.description ?? '', autoPort: false, udpPort: item.udp_port, sourceIp: item.allowed_source_ip, interfaceName: item.driver_parameters.interface, gatewayIp: item.driver_parameters.gateway_ip, enabled: item.enabled }); panelOpen.value = true }
async function save() { error.value = ''; saving.value = true; const body = { device_id: form.deviceId, name: form.name, description: form.description || null, udp_port: !isEditing.value && form.autoPort ? null : Number(form.udpPort), allowed_source_ip: form.sourceIp, driver_parameters: { interface: form.interfaceName, gateway_ip: form.gatewayIp }, enabled: form.enabled }; try { if (editingId.value) await api.updateListener(editingId.value, { ...body, version: form.version, udp_port: Number(form.udpPort) }); else await api.createListener(body); panelOpen.value = false; await load() } catch (reason) { error.value = readableError(reason) } finally { saving.value = false } }
async function remove(item: Listener) { if (!window.confirm(`Delete listener “${item.name}” on UDP ${item.udp_port}?`)) return; try { await api.deleteListener(item.id); await load() } catch (reason) { error.value = readableError(reason) } }
async function copyGuacamole(item: Listener) { await navigator.clipboard.writeText(`Wake-on-LAN Broadcast Address: <WOLT_HOST>\nWake-on-LAN UDP Port: ${item.udp_port}`) }
onMounted(load)
</script>
<template><AppShell :theme="theme" @toggle-theme="emit('toggleTheme')"><section class="page-heading"><div><p class="eyebrow">WAKE ENGINE / LISTENERS</p><h1>Listener mappings</h1><p>Each dedicated UDP port selects one device, interface, and destination network.</p></div><button class="primary-button button-link" :disabled="!enabledDevices.length" type="button" @click="openCreate"><Plus :size="16" /> Add listener</button></section>
<p v-if="error" class="form-error page-error">{{ error }}</p><div v-if="loading" class="panel loading-panel"><LoaderCircle class="spin" /> Loading listeners…</div><div v-else-if="!listeners.length" class="panel placeholder-panel"><div class="placeholder-icon"><RadioTower :size="28" /></div><h2>No listener mappings</h2><p>{{ enabledDevices.length ? 'Create a mapping and choose automatic or manual port allocation.' : 'Add and enable an edge device before creating a listener.' }}</p><button v-if="enabledDevices.length" class="primary-button" type="button" @click="openCreate"><Plus :size="15" /> Add first listener</button><RouterLink v-else class="primary-button button-link" to="/devices">Add edge device</RouterLink></div>
<section v-else class="panel operations-table"><header><span>UDP range <code>40000–40099</code></span><strong>{{ listeners.length }} used</strong></header><div class="table-wrap"><table><thead><tr><th>Status</th><th>Name</th><th>UDP port</th><th>Device</th><th>Interface</th><th>Gateway IP</th><th>Allowed source</th><th>Actions</th></tr></thead><tbody><tr v-for="item in listeners" :key="item.id"><td><span class="status-pill" :data-state="item.status">{{ item.status }}</span></td><td><strong>{{ item.name }}</strong><small>{{ item.enabled ? 'Enabled' : 'Disabled' }}</small></td><td><code>{{ item.udp_port }}</code></td><td>{{ item.device_name }}</td><td><code>{{ item.driver_parameters.interface }}</code></td><td><code>{{ item.driver_parameters.gateway_ip }}</code></td><td><code>{{ item.allowed_source_ip }}</code></td><td><div class="row-actions"><button title="Copy Guacamole values" @click="copyGuacamole(item)"><Copy :size="14" /></button><button title="Edit" @click="openEdit(item)"><Pencil :size="14" /></button><button class="danger-action" title="Delete" @click="remove(item)"><Trash2 :size="14" /></button></div></td></tr></tbody></table></div></section>
<div v-if="panelOpen" class="modal-backdrop" @click.self="panelOpen = false"><section class="side-panel" role="dialog" aria-modal="true"><header><div><p class="eyebrow">PORT → NETWORK CONTRACT</p><h2>{{ isEditing ? 'Edit listener' : 'Add listener' }}</h2></div><button class="icon-button" @click="panelOpen = false"><X :size="17" /></button></header><form class="operations-form" @submit.prevent="save"><label>Listener name<input v-model.trim="form.name" required maxlength="120" placeholder="VLAN 16 workstations" /></label><label>Description<textarea v-model.trim="form.description" rows="2"></textarea></label><label>Edge device<select v-model="form.deviceId" required><option v-for="device in enabledDevices" :key="device.id" :value="device.id">{{ device.name }}</option></select></label><label v-if="!isEditing" class="toggle-label"><input v-model="form.autoPort" type="checkbox" /><span>Auto assign the lowest available UDP port</span></label><label v-if="isEditing || !form.autoPort">UDP port<input v-model.number="form.udpPort" type="number" min="40000" max="40099" required /></label><label>Allowed PAM / guacd source IP<input v-model.trim="form.sourceIp" required placeholder="192.0.2.67" /></label><div class="form-row"><label>FortiGate interface<input v-model.trim="form.interfaceName" required placeholder="demo-vlan-16" /></label><label>Gateway / broadcast IP<input v-model.trim="form.gatewayIp" required placeholder="198.51.100.94" /></label></div><label class="toggle-label"><input v-model="form.enabled" type="checkbox" /><span>Enable this listener</span></label><div class="contract-preview"><code>WOLT_HOST:{{ form.autoPort && !isEditing ? 'AUTO' : form.udpPort }}</code><span>→</span><code>{{ form.interfaceName || 'interface' }}</code></div><p v-if="error" class="form-error">{{ error }}</p><footer><button class="secondary-button" type="button" @click="panelOpen = false">Cancel</button><button class="primary-button" :disabled="saving" type="submit"><LoaderCircle v-if="saving" class="spin" :size="15" /><CheckCircle2 v-else :size="15" /> Save listener</button></footer></form></section></div>
</AppShell></template>
