<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Clock3, Database, LoaderCircle, Play, Save, ShieldCheck } from '@lucide/vue'
import { api, readableError, type ApplicationSettings } from '../api'
import AppShell from '../components/AppShell.vue'

defineProps<{ theme: 'light' | 'dark' }>(); const emit = defineEmits<{ toggleTheme: [] }>()
const settings = ref<ApplicationSettings | null>(null); const form = reactive({ wake: 90, audit: 365, rate: 30 }); const loading = ref(true); const saving = ref(false); const cleaning = ref(false); const error = ref(''); const notice = ref('')
async function load() { loading.value = true; error.value = ''; try { settings.value = await api.settings(); Object.assign(form, { wake: settings.value.wake_event_retention_days, audit: settings.value.audit_event_retention_days, rate: settings.value.rate_limit_seconds }) } catch (reason) { error.value = readableError(reason) } finally { loading.value = false } }
async function save() { saving.value = true; error.value = ''; notice.value = ''; try { settings.value = await api.updateRetention({ wake_event_retention_days: Number(form.wake), audit_event_retention_days: Number(form.audit), rate_limit_seconds: Number(form.rate) }); notice.value = 'Runtime and retention settings saved.' } catch (reason) { error.value = readableError(reason) } finally { saving.value = false } }
async function cleanup() { if (!window.confirm('Delete events, audit records, and expired sessions older than the configured retention periods?')) return; cleaning.value = true; error.value = ''; notice.value = ''; try { const result = await api.runRetention(); notice.value = result.acquired ? `Cleanup completed: ${result.wake_events} events, ${result.audit_events} audit records, and ${result.sessions} sessions removed.` : 'Another cleanup job is already running.' } catch (reason) { error.value = readableError(reason) } finally { cleaning.value = false } }
onMounted(load)
</script>

<template><AppShell :theme="theme" @toggle-theme="emit('toggleTheme')">
  <section class="page-heading"><div><p class="eyebrow">ADMINISTRATION / SETTINGS</p><h1>Runtime data policy</h1><p>Control rate limiting and the lifecycle of operational records.</p></div></section>
  <div v-if="loading" class="panel loading-panel"><LoaderCircle class="spin" /> Loading settings…</div><template v-else-if="settings"><p v-if="error" class="form-error page-error">{{ error }}</p><p v-if="notice" class="form-success page-error">{{ notice }}</p><section class="settings-layout"><form class="panel settings-card operations-form" @submit.prevent="save"><header><span class="metric-glyph"><Clock3 :size="15" /></span><div><h2>Retention and rate control</h2><p>Changes are recorded in the audit trail.</p></div></header><div class="form-row"><label>Wake event retention (days)<input v-model.number="form.wake" type="number" min="1" max="3650" required /><small>Operational wake outcomes and correlation metadata.</small></label><label>Audit retention (days)<input v-model.number="form.audit" type="number" min="30" max="3650" required /><small>Administrative audit history; minimum 30 days.</small></label></div><label>Per-MAC rate limit (seconds)<input v-model.number="form.rate" type="number" min="0" max="3600" required /><small>Set to 0 only when temporary rate limiting is intentionally disabled.</small></label><footer><button class="primary-button" :disabled="saving" type="submit"><LoaderCircle v-if="saving" class="spin" :size="15" /><Save v-else :size="15" /> Save policy</button></footer></form><aside class="panel settings-card"><header><span class="metric-glyph"><Database :size="15" /></span><div><h2>Storage housekeeping</h2><p>An hourly background worker applies this policy.</p></div></header><dl><div><dt>UDP listener range</dt><dd><code>{{ settings.udp_port_start }}–{{ settings.udp_port_end }}</code></dd></div><div><dt>Application timezone</dt><dd>{{ settings.timezone }}</dd></div><div><dt>Locale</dt><dd>{{ settings.locale }}</dd></div><div><dt>Last settings update</dt><dd>{{ new Date(settings.updated_at).toLocaleString() }}</dd></div></dl><div class="retention-note"><ShieldCheck :size="16" /><p>Cleanup uses a PostgreSQL advisory lock, so only one instance can delete retained data at a time.</p></div><button class="secondary-button button-link" :disabled="cleaning" @click="cleanup"><LoaderCircle v-if="cleaning" class="spin" :size="15" /><Play v-else :size="15" /> Run cleanup now</button></aside></section></template><p v-else class="form-error page-error">{{ error }}</p>
</AppShell></template>
