<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { Clock3, Database, LoaderCircle, Network, PackageCheck, Play, Save, ShieldCheck } from '@lucide/vue'
import { api, readableError, type ApplicationSettings, type SystemInfo } from '../api'
import AppShell from '../components/AppShell.vue'

defineProps<{ theme: 'light' | 'dark' }>(); const emit = defineEmits<{ toggleTheme: [] }>()
const settings = ref<ApplicationSettings | null>(null); const systemInfo = ref<SystemInfo | null>(null)
const policy = reactive({ wake: 90, audit: 365, rate: 30 }); const udp = reactive({ start: 40000, end: 40099 })
const loading = ref(true); const savingPolicy = ref(false); const savingUdp = ref(false); const cleaning = ref(false); const error = ref(''); const notice = ref('')
const udpWidth = computed(() => Number(udp.end) - Number(udp.start) + 1)
const udpValidation = computed(() => {
  if (!settings.value) return ''
  if (udp.start < 1024 || udp.end > 65535) return 'UDP ports must be between 1024 and 65535.'
  if (udp.start > udp.end) return 'The start port must not exceed the end port.'
  if (udpWidth.value > 100) return 'The active range can contain at most 100 UDP ports.'
  if (udp.start < settings.value.udp_published_start || udp.end > settings.value.udp_published_end) return 'The active range must remain inside the Docker-published range.'
  return ''
})
async function load() { loading.value = true; error.value = ''; try { [settings.value, systemInfo.value] = await Promise.all([api.settings(), api.systemInfo()]); Object.assign(policy, { wake: settings.value.wake_event_retention_days, audit: settings.value.audit_event_retention_days, rate: settings.value.rate_limit_seconds }); Object.assign(udp, { start: settings.value.udp_port_start, end: settings.value.udp_port_end }) } catch (reason) { error.value = readableError(reason) } finally { loading.value = false } }
async function savePolicy() { savingPolicy.value = true; error.value = ''; notice.value = ''; try { settings.value = await api.updateRetention({ wake_event_retention_days: Number(policy.wake), audit_event_retention_days: Number(policy.audit), rate_limit_seconds: Number(policy.rate) }); notice.value = 'Runtime and retention policy saved.' } catch (reason) { error.value = readableError(reason) } finally { savingPolicy.value = false } }
async function saveUdp() { if (udpValidation.value) return; savingUdp.value = true; error.value = ''; notice.value = ''; try { settings.value = await api.updateUdpRange({ udp_port_start: Number(udp.start), udp_port_end: Number(udp.end) }); notice.value = 'Active UDP allocation range saved and the engine reconciled.' } catch (reason) { error.value = readableError(reason) } finally { savingUdp.value = false } }
async function cleanup() { if (!window.confirm('Delete events, audit records, and expired sessions older than the configured retention periods?')) return; cleaning.value = true; error.value = ''; notice.value = ''; try { const result = await api.runRetention(); notice.value = result.acquired ? `Cleanup completed: ${result.wake_events} events, ${result.audit_events} audit records, and ${result.sessions} sessions removed.` : 'Another cleanup job is already running.' } catch (reason) { error.value = readableError(reason) } finally { cleaning.value = false } }
onMounted(load)
</script>

<template><AppShell :theme="theme" @toggle-theme="emit('toggleTheme')">
  <section class="page-heading"><div><p class="eyebrow">ADMINISTRATION / SETTINGS</p><h1>Runtime configuration</h1><p>Control listener allocation, rate limiting, and the lifecycle of operational records.</p></div></section>
  <div v-if="loading" class="panel loading-panel"><LoaderCircle class="spin" /> Loading settings…</div>
  <template v-else-if="settings">
    <p v-if="error" class="form-error page-error" role="alert">{{ error }}</p><p v-if="notice" class="form-success page-error" role="status">{{ notice }}</p>
    <section class="settings-layout"><div class="settings-stack">
      <form class="panel settings-card operations-form" @submit.prevent="saveUdp"><header><span class="metric-glyph"><Network :size="16" /></span><div><h2>UDP listener allocation</h2><p>Choose the active range used for automatic and manual listener ports.</p></div></header><div class="range-boundary"><span>Docker-published boundary</span><code>{{ settings.udp_published_start }}–{{ settings.udp_published_end }}</code></div><div class="form-row equal"><label>Active start port<input v-model.number="udp.start" type="number" min="1024" max="65535" required /></label><label>Active end port<input v-model.number="udp.end" type="number" min="1024" max="65535" required /></label></div><div class="range-summary"><span><strong>{{ udpWidth > 0 ? udpWidth : 0 }}</strong> ports in range</span><span><strong>{{ settings.udp_ports_used }}</strong> currently used</span><span><strong>{{ Math.max(0, udpWidth - settings.udp_ports_used) }}</strong> potentially free</span></div><p v-if="udpValidation" class="form-error">{{ udpValidation }}</p><div class="retention-note"><ShieldCheck :size="16" /><p>WOLT rejects a range that excludes an existing listener or extends beyond ports published by Docker.</p></div><footer><button class="primary-button" :disabled="savingUdp || Boolean(udpValidation)" type="submit"><LoaderCircle v-if="savingUdp" class="spin" :size="15" /><Save v-else :size="15" /> Save UDP range</button></footer></form>
      <form class="panel settings-card operations-form" @submit.prevent="savePolicy"><header><span class="metric-glyph"><Clock3 :size="16" /></span><div><h2>Retention and rate control</h2><p>Policy changes are recorded in the administrative audit trail.</p></div></header><div class="form-row"><label>Wake event retention (days)<input v-model.number="policy.wake" type="number" min="1" max="3650" required /><small>Operational outcomes and correlation metadata.</small></label><label>Audit retention (days)<input v-model.number="policy.audit" type="number" min="30" max="3650" required /><small>Administrative history; minimum 30 days.</small></label></div><label>Per-MAC rate limit (seconds)<input v-model.number="policy.rate" type="number" min="0" max="3600" required /><small>Set to 0 only when rate limiting is intentionally disabled.</small></label><footer><button class="primary-button" :disabled="savingPolicy" type="submit"><LoaderCircle v-if="savingPolicy" class="spin" :size="15" /><Save v-else :size="15" /> Save policy</button></footer></form>
    </div><aside class="settings-stack">
      <section class="panel settings-card"><header><span class="metric-glyph"><PackageCheck :size="16" /></span><div><h2>Build information</h2><p>Use these values when reporting an issue or planning an upgrade.</p></div></header><dl><div><dt>Version</dt><dd><code>{{ systemInfo?.version ?? 'Unavailable' }}</code></dd></div><div><dt>Commit</dt><dd><code>{{ systemInfo?.commit_sha ?? 'Unavailable' }}</code></dd></div><div><dt>Build date</dt><dd>{{ systemInfo?.build_date ?? 'Unavailable' }}</dd></div><div><dt>Environment</dt><dd>{{ systemInfo?.environment ?? 'Unavailable' }}</dd></div><div><dt>Database revision</dt><dd><code>{{ systemInfo?.schema_revision ?? 'Unavailable' }}</code></dd></div></dl><div class="retention-note"><PackageCheck :size="16" /><p>Signed release discovery, digest-pinned upgrades, health verification, and rollback are available to Owners under <strong>Host operations</strong> after installing the restricted Host Agent.</p></div></section>
      <section class="panel settings-card"><header><span class="metric-glyph"><Database :size="16" /></span><div><h2>Storage housekeeping</h2><p>An hourly background worker applies the configured retention policy.</p></div></header><dl><div><dt>Active UDP range</dt><dd><code>{{ settings.udp_port_start }}–{{ settings.udp_port_end }}</code></dd></div><div><dt>Application timezone</dt><dd>{{ settings.timezone }}</dd></div><div><dt>Locale</dt><dd>{{ settings.locale }}</dd></div><div><dt>Last settings update</dt><dd>{{ new Date(settings.updated_at).toLocaleString() }}</dd></div></dl><div class="retention-note"><ShieldCheck :size="16" /><p>Cleanup uses a PostgreSQL advisory lock, so only one application instance can remove retained data at a time.</p></div><button class="secondary-button button-link" :disabled="cleaning" @click="cleanup"><LoaderCircle v-if="cleaning" class="spin" :size="15" /><Play v-else :size="15" /> Run cleanup now</button></section>
    </aside></section>
  </template><p v-else class="form-error page-error">{{ error }}</p>
</AppShell></template>
