<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { CheckCircle2, KeyRound, LoaderCircle, MailPlus, RefreshCw, Shield, UserRoundCog, X } from '@lucide/vue'
import { api, readableError, type ManagedUser } from '../api'
import AppShell from '../components/AppShell.vue'

defineProps<{ theme: 'light' | 'dark' }>(); const emit = defineEmits<{ toggleTheme: [] }>()
const users = ref<ManagedUser[]>([]); const loading = ref(true); const error = ref(''); const success = ref(''); const panelOpen = ref(false); const saving = ref(false)
const form = reactive({ username: '', email: '', role: 'administrator' })
async function load() { loading.value = true; error.value = ''; try { users.value = await api.users() } catch (reason) { error.value = readableError(reason) } finally { loading.value = false } }
function openInvite() { Object.assign(form, { username: '', email: '', role: 'administrator' }); panelOpen.value = true; success.value = '' }
async function invite() { saving.value = true; error.value = ''; try { await api.inviteUser(form); panelOpen.value = false; success.value = `Invitation sent to ${form.email}.`; await load() } catch (reason) { error.value = readableError(reason) } finally { saving.value = false } }
async function change(user: ManagedUser, values: Partial<Pick<ManagedUser, 'role' | 'enabled'>>) { error.value = ''; try { await api.updateUser(user.id, { role: values.role ?? user.role, enabled: values.enabled ?? user.enabled }); await load() } catch (reason) { error.value = readableError(reason) } }
function roleChange(user: ManagedUser, event: Event) { change(user, { role: (event.target as HTMLSelectElement).value }) }
async function revoke(user: ManagedUser) { if (!confirm(`Revoke all active sessions for ${user.username}?`)) return; try { await api.revokeUserSessions(user.id); success.value = `Sessions revoked for ${user.username}.`; await load() } catch (reason) { error.value = readableError(reason) } }
onMounted(load)
</script>

<template><AppShell :theme="theme" @toggle-theme="emit('toggleTheme')">
  <section class="page-heading"><div><p class="eyebrow">ADMINISTRATION / IDENTITY</p><h1>Users and sessions</h1><p>Invite administrators and operators, enforce least privilege, and revoke active access.</p></div><button class="primary-button button-link" type="button" @click="openInvite"><MailPlus :size="16" /> Invite user</button></section>
  <p v-if="error" class="form-error page-error" role="alert">{{ error }}</p><p v-if="success" class="form-success page-message"><CheckCircle2 :size="15" /> {{ success }}</p>
  <section class="panel identity-summary"><Shield :size="21" /><div><strong>Owner-controlled identity</strong><p>Invitations expire after 24 hours. Invitees set their own password; WOLT never emails a password.</p></div></section>
  <section v-if="loading" class="panel loading-panel"><LoaderCircle class="spin" /> Loading users…</section>
  <section v-else class="panel operations-table"><header><span>{{ users.length }} identities</span><button class="secondary-button" type="button" @click="load"><RefreshCw :size="14" /> Refresh</button></header><div class="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Sessions</th><th>Last login</th><th>Actions</th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td><strong>{{ user.username }}</strong><small>{{ user.email }}</small></td><td><select class="table-select" :value="user.role" @change="roleChange(user, $event)"><option value="owner">Owner</option><option value="administrator">Administrator</option><option value="operator">Operator</option></select></td><td><span class="status-pill" :data-state="user.status">{{ user.status }}</span></td><td>{{ user.active_sessions }}</td><td>{{ user.last_login_at ? new Date(user.last_login_at).toLocaleString() : 'Never' }}</td><td><div class="row-actions"><button type="button" :disabled="user.status === 'pending'" @click="change(user, { enabled: !user.enabled })">{{ user.enabled ? 'Disable' : 'Enable' }}</button><button type="button" :disabled="!user.active_sessions" @click="revoke(user)"><KeyRound :size="13" /> Revoke sessions</button></div></td></tr></tbody></table></div></section>
  <div v-if="panelOpen" class="modal-backdrop" @click.self="panelOpen = false"><section class="side-panel" role="dialog" aria-modal="true" aria-label="Invite user"><header><div><p class="eyebrow">SECURE INVITATION</p><h2>Invite a WOLT user</h2></div><button class="icon-button" type="button" @click="panelOpen = false"><X :size="17" /></button></header><form class="operations-form" @submit.prevent="invite"><div class="identity-invite"><UserRoundCog :size="19" /><p>The recipient receives a one-time link and chooses a password. Configure SMTP first.</p></div><label>Username<input v-model.trim="form.username" required minlength="3" maxlength="80" pattern="[A-Za-z0-9_.-]+" autocomplete="off" /></label><label>Email<input v-model.trim="form.email" required type="email" autocomplete="off" /></label><label>Role<select v-model="form.role"><option value="administrator">Administrator — manages operations</option><option value="operator">Operator — observes and controls engine</option></select></label><footer><button class="secondary-button" type="button" @click="panelOpen = false">Cancel</button><button class="primary-button" :disabled="saving" type="submit"><LoaderCircle v-if="saving" class="spin" :size="15" /><MailPlus v-else :size="15" /> Send invitation</button></footer></form></section></div>
</AppShell></template>
