listeners:
  "40016":
    interface: "demo-vlan-16"
    gateway_ip: "198.51.100.94"
  "40067":
    interface: "demo-vlan-67"
    gateway_ip: "203.0.113.30"
  "40090":
    interface: "demo-vlan-90"
    gateway_ip: "203.0.113.62"
